"""Coding tools, stateful sessions, and frontends built on rio_agent."""

from __future__ import annotations

from rio_coding.built_in_extensions import (
    BuiltInExtension,
    BuiltInExtensionSetup,
)
from rio_coding.coding_skill import CodingSkillOptions, build_coding_skill
from rio_coding.commands import (
    CommandRegistry,
    CommandResult,
    SlashCommand,
    create_default_command_registry,
)
from rio_coding.context import (
    discover_project_context,
    discover_project_context_with_diagnostics,
)
from rio_coding.credentials import (
    CredentialStoreError,
    FileCredentialStore,
    OAuthCredential,
    credentials_path,
)
from rio_coding.oauth_registry import (
    get_oauth_provider,
    get_oauth_providers,
    register_oauth_provider,
    reset_oauth_providers,
    unregister_oauth_provider,
)
from rio_coding.oauth_types import (
    OAuthAuthInfo,
    OAuthDeviceCodeInfo,
    OAuthLoginCallbacks,
    OAuthPrompt,
    OAuthProvider,
    OAuthRuntimeAuth,
)
from rio_coding.paths import (
    RioPaths,
)
from rio_coding.prompt_templates import (
    PromptTemplate,
    expand_prompt_template_command,
    load_prompt_templates,
    load_prompt_templates_with_diagnostics,
    parse_prompt_template_arguments,
    render_prompt_template,
    substitute_prompt_template_args,
)
from rio_coding.provider_catalog import (
    BUILTIN_PROVIDER_CATALOG,
    ProviderCatalogEntry,
    builtin_provider_entry,
)
from rio_coding.provider_config import (
    DEFAULT_MODEL,
    DEFAULT_PROVIDER_NAME,
    AnthropicProviderConfig,
    OpenAICodexProviderConfig,
    OpenAICompatibleProviderConfig,
    ProviderConfig,
    ProviderConfigError,
    ProviderSelection,
    ProviderSettings,
    ScopedModelConfig,
    anthropic_config_from_provider,
    builtin_provider_configs,
    default_openai_provider_config,
    load_provider_settings,
    openai_compatible_config_from_provider,
    provider_config_from_catalog_entry,
    provider_default_thinking_level,
    provider_has_usable_credentials,
    provider_kind,
    provider_settings_path,
    provider_thinking_levels,
    provider_thinking_unavailable_reason,
    resolve_provider_selection,
    resolve_startup_thinking_level,
    save_default_provider_model,
    save_provider_settings,
    toggle_saved_scoped_model,
    upsert_openai_compatible_provider,
    upsert_provider,
    upsert_saved_provider,
    validate_provider_model,
)
from rio_coding.rendering import (
    EventRenderer,
    JsonEventRenderer,
    PlainEventRenderer,
    PrintOutputMode,
    create_event_renderer,
)
from rio_coding.resources import (
    ResourceDiagnostic,
    ResourceError,
    RioResourcePaths,
)
from rio_coding.session import (
    CodingSession,
    CodingSessionConfig,
    ModelChoice,
    default_session_path,
    jsonl_session_storage,
)
from rio_coding.session_export import (
    SessionExportError,
    default_session_export_path,
    export_session_html,
    render_session_html,
)
from rio_coding.session_manager import (
    CodingSessionRecord,
    SessionManager,
)
from rio_coding.shell_config import (
    ShellConfigError,
    ShellSettings,
    load_shell_settings,
    shell_settings_from_json,
    shell_settings_path,
)
from rio_coding.skills import (
    Skill,
    build_skill_index,
    expand_skill_command,
    format_skill_invocation,
    load_skills,
    load_skills_with_diagnostics,
    parse_skill_invocation,
)
from rio_coding.step_footprint import StepFootprint, estimate_step_footprint
from rio_coding.system_prompt import (
    BuildSystemPromptOptions,
    ProjectContextFile,
    build_system_prompt,
    collect_prompt_guidelines,
    format_available_tools,
    format_guidelines,
    format_project_context,
    format_skills_for_prompt,
)
from rio_coding.thinking import (
    DEFAULT_THINKING_LEVEL,
    THINKING_LEVELS,
    ReasoningEffort,
    ThinkingLevel,
    ThinkingParameter,
    normalize_thinking_levels,
    reasoning_effort_for_level,
)
from rio_coding.tools import (
    ImageSupportState,
    ReadOperations,
    ToolDefinition,
    create_bash_tool,
    create_bash_tool_definition,
    create_coding_tools,
    create_edit_tool,
    create_edit_tool_definition,
    create_read_tool,
    create_read_tool_definition,
    create_write_tool,
    create_write_tool_definition,
)
from rio_coding.version import (
    current_version,
)

__version__ = current_version()

__all__ = [
    "AnthropicProviderConfig",
    "BUILTIN_PROVIDER_CATALOG",
    "BuildSystemPromptOptions",
    "BuiltInExtension",
    "BuiltInExtensionSetup",
    "CodingSession",
    "CodingSessionConfig",
    "ModelChoice",
    "CodingSessionRecord",
    "CodingSkillOptions",
    "CommandRegistry",
    "CommandResult",
    "CredentialStoreError",
    "DEFAULT_MODEL",
    "DEFAULT_PROVIDER_NAME",
    "DEFAULT_THINKING_LEVEL",
    "EventRenderer",
    "FileCredentialStore",
    "ImageSupportState",
    "JsonEventRenderer",
    "OAuthAuthInfo",
    "OAuthCredential",
    "OAuthDeviceCodeInfo",
    "OAuthLoginCallbacks",
    "OAuthPrompt",
    "OAuthProvider",
    "OAuthRuntimeAuth",
    "OpenAICodexProviderConfig",
    "OpenAICompatibleProviderConfig",
    "PlainEventRenderer",
    "PrintOutputMode",
    "ProjectContextFile",
    "PromptTemplate",
    "ProviderCatalogEntry",
    "ProviderConfig",
    "ProviderConfigError",
    "ProviderSelection",
    "ProviderSettings",
    "ReadOperations",
    "ReasoningEffort",
    "ResourceDiagnostic",
    "ResourceError",
    "RioPaths",
    "RioResourcePaths",
    "ScopedModelConfig",
    "SessionExportError",
    "SessionManager",
    "ShellConfigError",
    "ShellSettings",
    "Skill",
    "SlashCommand",
    "StepFootprint",
    "THINKING_LEVELS",
    "ThinkingLevel",
    "ThinkingParameter",
    "ToolDefinition",
    "__version__",
    "anthropic_config_from_provider",
    "build_coding_skill",
    "build_skill_index",
    "build_system_prompt",
    "builtin_provider_configs",
    "builtin_provider_entry",
    "collect_prompt_guidelines",
    "create_bash_tool",
    "create_bash_tool_definition",
    "create_coding_tools",
    "create_default_command_registry",
    "create_edit_tool",
    "create_edit_tool_definition",
    "create_event_renderer",
    "create_read_tool",
    "create_read_tool_definition",
    "create_write_tool",
    "create_write_tool_definition",
    "credentials_path",
    "current_version",
    "default_openai_provider_config",
    "default_session_export_path",
    "default_session_path",
    "discover_project_context",
    "discover_project_context_with_diagnostics",
    "estimate_step_footprint",
    "expand_prompt_template_command",
    "expand_skill_command",
    "export_session_html",
    "format_available_tools",
    "format_guidelines",
    "format_project_context",
    "format_skill_invocation",
    "format_skills_for_prompt",
    "get_oauth_provider",
    "get_oauth_providers",
    "jsonl_session_storage",
    "load_prompt_templates",
    "load_prompt_templates_with_diagnostics",
    "load_provider_settings",
    "load_shell_settings",
    "load_skills",
    "load_skills_with_diagnostics",
    "normalize_thinking_levels",
    "openai_compatible_config_from_provider",
    "parse_prompt_template_arguments",
    "parse_skill_invocation",
    "provider_config_from_catalog_entry",
    "provider_default_thinking_level",
    "provider_has_usable_credentials",
    "provider_kind",
    "provider_settings_path",
    "provider_thinking_levels",
    "provider_thinking_unavailable_reason",
    "reasoning_effort_for_level",
    "register_oauth_provider",
    "render_prompt_template",
    "render_session_html",
    "reset_oauth_providers",
    "resolve_provider_selection",
    "resolve_startup_thinking_level",
    "save_default_provider_model",
    "save_provider_settings",
    "shell_settings_from_json",
    "shell_settings_path",
    "substitute_prompt_template_args",
    "toggle_saved_scoped_model",
    "unregister_oauth_provider",
    "upsert_openai_compatible_provider",
    "upsert_provider",
    "upsert_saved_provider",
    "validate_provider_model",
]
